### ISSUE TITLE
Practica 3

### ISSUE THREAD

**Issue by UsuarioIncognito** [SistemasTecTlaxiaco/actividad-12-ejercicios-de-mapas-de-karnaught-pavos2#1]
[PRACTICA_3_MATESDISCRETAS.pdf](https://github.com/user-attachments/files/18067838/PRACTICA_3_MATESDISCRETAS.pdf)

**Comment by Irwingferia** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
